export const SET_EMAIL = 'SET_EMAIL'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_FORM_LOADING = 'SET_FORM_LOADING'

export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'

export const AUTHENTICATE = 'AUTHENTICATE'
